apiVersion: apps/v1
kind: Deployment
metadata:
  name: urbangear-frontend
spec:
  template:
    spec:
      containers:
      - name: frontend
        image: 484907531725.dkr.ecr.us-west-2.amazonaws.com/urbangear-dev-frontend:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"