apiVersion: apps/v1
kind: Deployment
metadata:
  name: urbangear-frontend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: frontend
        image: 924612597584.dkr.ecr.us-east-1.amazonaws.com/urbangear-dev-frontend:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"

# CI: pipeline test 2025-11-20