apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml

replicas:
- name: urbangear-frontend
  count: 3

commonLabels:
  environment: prod

images:
- name: PLACEHOLDER_ECR_URI
  newTag: latest