apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

commonLabels:
  project: urbangear
  environment: dev

images:
- name: PLACEHOLDER_ECR_URI
  newTag: latest