apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

labels:
- pairs:
    project: urbangear
    environment: dev
  includeSelectors: true
  includeTemplates: true

images:
- name: PLACEHOLDER_ECR_URI
  newTag: latest