apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: urbangear-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Rahulx0/DEVOPS-project.git
    targetRevision: rahul
    path: manifests/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
