name: Build and Deploy

on:
  push:
    branches:
      - main
      - rahul
  pull_request:
    branches:
      - main
      - rahul

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
  KUBE_NAMESPACE: default

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image-tag: ${{ steps.image.outputs.tag }}
      image-uri: ${{ steps.image.outputs.uri }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image to Amazon ECR
        id: build-image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile
          target: prod
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

      - name: Set image metadata outputs
        id: image
        run: |
          echo "tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          echo "uri=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Update deployment manifest
        run: |
          sed -i 's|484907531725.dkr.ecr.us-west-2.amazonaws.com/urbangear-dev-frontend:latest|${{ steps.image.outputs.uri }}|g' manifests/overlays/prod/deployment-patch.yaml

      - name: Upload updated manifest
        uses: actions/upload-artifact@v4
        with:
          name: deployment-manifest
          path: manifests/overlays/prod/deployment-patch.yaml

  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: build
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/rahul') && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

      - name: Download deployment manifest
        uses: actions/download-artifact@v4
        with:
          name: deployment-manifest
          path: manifests/overlays/prod

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -k manifests/overlays/prod/

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/urbangear-frontend -n ${{ env.KUBE_NAMESPACE }} --timeout=5m

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd app && npm ci

      - name: Build application
        run: |
          cd app && npm run build

      - name: Run linter
        run: |
          cd app && npm run lint 2>/dev/null || true

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: '.'
          format: sarif
          output: trivy-results.sarif

      - name: Upload Trivy results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
